spring.application.name=basicspringboot
spring.datasource.url=jdbc:mysql://localhost:3306/springBasics?createDatabaseIfNotExist=true
spring.datasource.username=username
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update